name: seeker
description: 'ITI Placements App'
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.7.2

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  go_router: ^14.8.1
  flutter_riverpod: ^2.6.1
  dio: ^5.8.0+1
  flutter_secure_storage: ^9.2.4
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  flutter_form_builder: ^10.0.1
  intl: ^0.20.2
  logger: ^2.5.0
  freezed_annotation: ^3.0.0
  url_launcher: ^6.3.1
  phone_number: ^2.1.0
  flutter_native_splash: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0
  freezed: ^3.0.4
  build_runner: ^2.4.15

  # build_runner: ^2.4.11 # Needed for code generation (e.g., Riverpod, Freezed)
  # riverpod_generator: ^2.4.0 # If using Riverpod code generation
  # freezed: ^2.5.2 # If using Freezed for immutable models
  # freezed_annotation: ^2.4.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/onest-logo.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
# flutter_launcher_icons:
#   android: true # Generate icons for Android
#   ios: true # Generate icons for iOS
#   image_path: 'assets/logo.png' # Path to YOUR logo file
#   min_sdk_android: 21 # Optional: Set minimum Android SDK

#   # --- Optional: Adaptive Icons for Android (Android 8.0+) ---
#   # You might need a separate background color/image and foreground image
#   # If your logo is simple and looks okay on a plain background:
#   adaptive_icon_background: '#FFFFFF' # Example: White background
#   adaptive_icon_foreground: 'assets/logo.png' # Use your logo as foreground

# --- Optional: Web/Windows/macOS ---
# web:
#   generate: true
#   image_path: "path/to/icon.png"
#   background_color: "#hexcode"
#   theme_color: "#hexcode"
# windows:
#   generate: true
#   image_path: "path/to/icon.png"
#   icon_size: 48 # min:48, max:256, default: 48
# macos:
#   generate: true
#   image_path: "path/to/icon.png"

flutter_native_splash:
  # The background color for the native splash screen
  # Use a hex color string (e.g., your app's main background or brand color)
  color: '#ffffff' # Example: White background

  # The path to your logo asset (relative to the project root)
  image: assets/logo.png

  # Optional: Set 'android: true' and 'ios: true' if you want to explicitly enable for platforms
  # By default, it runs for both if they exist.
  android: true
  ios: true
